# Generated by Django 3.2.4 on 2021-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='batch_code',
            field=models.CharField(default='uxzsrvaouj', max_length=10),
        ),
    ]
